import { ChangeDetectionStrategy, Component, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-landing-page',
  imports: [],
  template: `
    <p>First line</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>landing-page works!</p>
    <p>yes landing-page works!</p>
  `,
  styles: ``,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export default class LandingPage {}
